telegram_token: "8039269123123123059:123123123"
deepseek_api_url: "https://api.deepseek.com/v1/chat/completions"
deepseek_api_key: "sk-123123123"
trigger_probability: 0.1
chat_id: -1001393262528
deepseek_model: "deepseek-chat"
max_tokens: 150
temperature: 0.8
